/*

This is the home page of the application. It will display the user's NFTs and allow them to mint and destroy NFTs.
This page is used to demonstrate the CHILD ACCOUNT.  The parent account is used in the pages/parent.tsx file.

*/

import Head from "next/head";
import { useFlow } from "../contexts/FlowContext";
import { Button, Flex, Heading, Spinner, Text } from "@chakra-ui/react";
import { useNFTs } from "../hooks/useNFTs";
import NFTGrid from "../components/NFTGrid";
import mintNFTCadence from "../cadence/transactions/example-nft/mint_nft.cdc";
import destroyNFTCadence from "../cadence/transactions/example-nft/destroy_nft.cdc";
import * as fcl from "@onflow/fcl";

export default function Home() {
  const flow = useFlow();
  const { nfts, mutate: mutateNFTs } = useNFTs();

  // This is a function that will be called when the user clicks the "Mint NFT" button
  async function mintNFT() {
    return fcl
      .mutate({
        cadence: mintNFTCadence,
        limit: 9999,
        authz: flow.authz,
        args: (arg: any, t: any) => [arg(null, t.Optional(t.Address))],
      } as any)
      .then((txId) => fcl.tx(txId).onceSealed())
      .then((status) => {
        if (status.errorMessage) {
          throw new Error(status.errorMessage);
        }
        mutateNFTs();
      });
  }

  // This is a function that will be called when the user clicks the "Destroy NFT" button
  async function destroyNFT(id: string) {
    return fcl
      .mutate({
        cadence: destroyNFTCadence,
        limit: 9999,
        authz: flow.authz,
        args: (arg: any, t: any) => [arg(id, t.UInt64)],
      } as any)
      .then((txId) => fcl.tx(txId).onceSealed())
      .then((status) => {
        if (status.errorMessage) {
          throw new Error(status.errorMessage);
        }
        mutateNFTs();
      });
  }

  return (
    <>
      <Head>
        <title>Flow Magic Link HC</title>
        <meta
          name="description"
          content="A demo of the Flow Magic Link Hybrid Custody pattern"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column" gap={8}>
        <Heading>Child Account (App)</Heading>

        <Text>
          You are currently viewing your NFTs on the &quot;child account&quot;
          which has been transparently generated by the application.
          Transactions in this mode will run{" "}
          <b>without any additional approvals.</b>
        </Text>

        {flow.isLoggedIn === null ? (
          <Flex justifyContent="center">
            <Spinner size="lg" />
          </Flex>
        ) : flow.isLoggedIn ? (
          <NFTGrid
            nfts={nfts}
            onMintNFT={mintNFT}
            onDestroyNFT={(id) => destroyNFT(id)}
          ></NFTGrid>
        ) : (
          <Flex flexDirection="column" gap={4} pt={4}>
            <Flex justifyContent="center">
              <Text fontWeight="bold" fontSize="lg">
                To get started, you must sign in or sign up
              </Text>
            </Flex>
            <Flex justifyContent="center">
              <Button colorScheme="blue" size="lg" onClick={() => flow.login()}>
                Login/Signup
              </Button>
            </Flex>
          </Flex>
        )}
      </Flex>
    </>
  );
}
